### ISSUE TITLE
URL Redirect 2016.opentechsummit.net to opentechsummit.net

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#1]

**Comment by shivamMg** [comment]
@mariobehling Doesn't the domain provider for 2016.opentechsummit.net provide such service, because some of them do. Else we can do it with a php file.

**Comment by aviaryan** [comment]
Yes the domain providers (godaddy or anyone else) do provide such a feature.
@shivamMg Php is out of the question because the site is hosted on github. (CNAME file)

**Comment by mariobehling** [comment]
I will do it, when I have time.

**Comment by jigyasa-grover** [comment]
@mariobehling Works fine. 
Closing this issue.

**Comment by mananwason** [comment]
@jig08 No it doesn't. Ideally it should redirect to http://opentechsummit.net.
