### ISSUE TITLE
Schedule: Error in twitter links

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#15]
When I access http://opentechsummit.net/programm/, as I want to go to the Twitter profile of any of the speakers, I get a link to e.g. http://opentechsummit.net/programm/@picotcp where actually it should be e.g. https://twitter.com/@picotcp
It happens only in some profiles. With Twitter and with Github links.
[via Pablo]

**Comment by aviaryan** [comment]
The scraper needs to be fixed. https://github.com/OpenTechSummit/open-event-scraper/blob/master/scraper.py 
If we can fix the twitter and github url's generated from the scraper, then this issue will be fixed

PS - I was going to assign this to myself, just got a little late :disappointed:

**Comment by niranjan94** [comment]
@aviaryan wanna take it up ?

**Comment by aviaryan** [comment]
Yes. Thanks

**Comment by aviaryan** [comment]
Opened PR https://github.com/OpenTechSummit/open-event-scraper/pull/9
