### ISSUE TITLE
Links and Bio of speakers set to "none" when empty

### ISSUE THREAD

**Issue by aviaryan** [OpenTechSummit/2016.opentechsummit.net#16]
For example, see Sandra Müllrick 's bio on http://opentechsummit.net/programm/

Also there are lot of links pointing to github.com/none and twitter.com/none 

I am not sure about the "none" in bio part, maybe this is by design but the links pointing to _none_ is defintetly an issue.

**Comment by aviaryan** [comment]
It looks like the 'none' comes from the spreadsheet itself rather than some fault in the scraper. I saw the spreadsheet and saw 2 speakers (row 21 and 22) have `none` in their github link fields. Also the bio field for Sandra is 'none' where it could have been empty. 
So fixing those ambiguities and then running the travis will fix this issue.

**Comment by aviaryan** [comment]
> It looks like the 'none' comes from the spreadsheet itself rather than some fault in the scraper. I saw the spreadsheet and saw 2 speakers (row 21 and 22) have none in their github link fields. Also the bio field for Sandra is 'none' where it could have been empty. 
> So fixing those ambiguities and then running the travis will fix this issue.

@mariobehling Should I do this ?

**Comment by championswimmer** [comment]
For safety let's keep a check for field == 'none' and disable the field in client side js too ? 

@mariobehling  @aviaryan

**Comment by mariobehling** [comment]
@championswimmer Speakers just wrote "none" because that field is required. Let's delete it in the spreadsheet and fill in sth. relevant later. Closing this issue therefore.
