### ISSUE TITLE
Clicking on the "link symbol" results in an expanding area with a link, that is pre-activated and can be copied

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#22]
Currently we have a simple link symbol. We would like to improve this feature similar to the "get a link feature" on youtube and other service. 

Clicking on the "link symbol" should result in an expanding area with a link, that is pre-activated and can be copied.

![screenshot from 2016-04-26 22 57 57](https://cloud.githubusercontent.com/assets/1583873/14834127/120f93ae-0c03-11e6-86a8-3f75bd6681f1.png)

Result should be something similar to this:

![screenshot from 2016-04-26 22 57 57a](https://cloud.githubusercontent.com/assets/1583873/14834139/1b208e9e-0c03-11e6-9dbe-26849c9bb340.png)

**Comment by aayusharora** [comment]
@mariobehling , I want to work for it .

**Comment by SaptakS** [comment]
We need to merge this https://github.com/OpenTechSummit/open-event-scraper/pull/14 first. Otherwise the link generated on click is wrong presently. We will need to merge the PR to get the correct link.

**Comment by SaptakS** [comment]
Fixed using https://github.com/OpenTechSummit/open-event-scraper/issues/12, https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/27, https://github.com/OpenTechSummit/open-event-scraper/pull/14

**Comment by mariobehling** [comment]
@SaptakS @niranjan94 Could you take out the slow expanding effect out, please? Just let the area expand. Also, should we use the same font/size as the heading for the text or a bit smaller?

**Comment by niranjan94** [comment]
Will do it an an hour once I get home. If anyone else can do it before that
and would like to do it , please reply comment here and proceed.

**Comment by shivamMg** [comment]
@niranjan94 I can take it up.

**Comment by shivamMg** [comment]
@mariobehling I've reduced the font-size [here](https://github.com/OpenTechSummit/2016.opentechsummit.net/pull/30). [This](https://github.com/OpenTechSummit/open-event-scraper/pull/18) takes care of the sliding toggle issue.
