### ISSUE TITLE
Schedule: Add a video icon link behind talk, if a video link is defined in JSON

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#23]
There is a video column now in the spreadsheet. The scraper can get the link from that column.

Please add a video icon link to the session (as shown below), if a link is defined.

![screenshot from 2016-04-26 22 57 57b](https://cloud.githubusercontent.com/assets/1583873/14834571/7014ad7a-0c05-11e6-89eb-27fa74b2ff09.png)

**Comment by mariobehling** [comment]
@niranjan94 Please keep the icons in lign. Also the size should be similar. Nevertheless, we also want the icons to be easily clickable on mobile. Any suggestions?

![screenshot from 2016-04-27 08 37 01](https://cloud.githubusercontent.com/assets/1583873/14843804/667720f6-0c53-11e6-9ddf-c2357831e24a.png)

**Comment by niranjan94** [comment]
Resolved by PR OpenTechSummit/open-event-scraper#10

**Comment by niranjan94** [comment]
@mariobehling I'll align it ... For mobile, we could have bigger buttons that are displayed on a new line.

Like: 
![capture](https://cloud.githubusercontent.com/assets/2404372/14843993/e68e0af2-0c71-11e6-9580-6070b3597841.PNG)
