### ISSUE TITLE
Schedule: Add a slideshow link, if link is defined

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#24]
As in sample below:

![screenshot from 2016-04-26 22 57 57c](https://cloud.githubusercontent.com/assets/1583873/14834774/8f9f7480-0c06-11e6-971a-e3e6d92c60c1.png)

**Comment by SaptakS** [comment]
There is no column for slides or videos. Where are the links for sildes and videos? Can you give an example?

**Comment by niranjan94** [comment]
Resolved by PR OpenTechSummit/open-event-scraper#10
