### ISSUE TITLE
Add social media icons on top right. Generate them from JSON

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#3]
The spreadsheet where the JSON is generated from includes a sheet "Event" with links to the event and social media. Please include social media that have links in the page, when it is generated as shown in the picture.

![8e1e6a60-e840-11e5-8535-5d67b6fcf176](https://cloud.githubusercontent.com/assets/1583873/14770614/acc7220c-0a75-11e6-9134-3cc246ee8f88.png)

**Comment by aayusharora** [comment]
@mariobehling  , Please point me to the JSON you are talking about .

**Comment by mananwason** [comment]
@aayusharora This is the JSON https://github.com/OpenTechSummit/open-event-scraper/tree/master/out

**Comment by mariobehling** [comment]
@mananwason Please do not share the spreadsheet URL publicly as there is private contact data in there. Thank you.

**Comment by mananwason** [comment]
Sorry @mariobehling 😄

**Comment by aayusharora** [comment]
@aviaryan , Can you help me in this ?

**Comment by aviaryan** [comment]
@aayusharora Sure. What can I do ?

**Comment by championswimmer** [comment]
/note : fa-facebook fa-twitter can be used from fontawesome (already being used in the page)

**Comment by championswimmer** [comment]
@mariobehling We need to generate icons for all these services? https://github.com/OpenTechSummit/open-event-scraper/blob/master/out/services.json

**Comment by mariobehling** [comment]
@championswimmer Yes, please - just like shown on the top right in the mockup above.

**Comment by mariobehling** [comment]
@championswimmer Yes, please - just like shown on the top right in the mockup above.

**Comment by mariobehling** [comment]
@championswimmer Yes, please - just like shown on the top right in the mockup above.

**Comment by mariobehling** [comment]
@championswimmer 
- [x] Please adapt the script in the way, that only icons are generated that have a link (where the field is not empty). 
- [x] Please avoid empty spaces in the middle
- [x] Choose the "play" version of Youtube instead of the youtube logo. A video could also come from another service. Cheers.

![screenshot from 2016-04-27 08 38 43](https://cloud.githubusercontent.com/assets/1583873/14843813/7edbcc46-0c53-11e6-913d-4310abbf6651.png)

**Comment by mariobehling** [comment]
@championswimmer Well, in the spreadsheet "YouTube" is defined, but I would still vouch for using the other icon as most people just use one video service.

**Comment by mariobehling** [comment]
@championswimmer When you make PRs could you also please show new live features on your repository in action, please? Please provide a link to the program on your github account for example.

**Comment by mariobehling** [comment]
- [ ] In small screen/mobile version, please keep the icons in the main bar. Currently they are moving down.

![screenshot from 2016-04-27 08 59 11](https://cloud.githubusercontent.com/assets/1583873/14844265/82aec62c-0c56-11e6-842d-b17b55d5ffd9.png)

**Comment by championswimmer** [comment]
Ok making the changes and adding to this PR

**Comment by SaptakS** [comment]
@championswimmer for creating the json for service, the build.sh and run.sh needs to be modified. You have to include `python event.py` in both the files

**Comment by championswimmer** [comment]
@mariobehling 
my and @shivamMg 's commits in this PR https://github.com/OpenTechSummit/open-event-scraper/pull/16 should solve all the mentioned issues.

**Comment by mariobehling** [comment]
@championswimmer  The icons are still moving down. Should stay in line with the main menu.
![screenshot from 2016-04-27 18 10 43](https://cloud.githubusercontent.com/assets/1583873/14859274/bec5d950-0ca3-11e6-922d-b4410bb7bdff.png)

**Comment by aayusharora** [comment]
@mariobehling , @mananwason Can I take this ?

**Comment by aayusharora** [comment]
![1](https://cloud.githubusercontent.com/assets/12194719/14861287/31a9d720-0cca-11e6-9a0a-abfaaf29f9d0.png)

**Comment by aayusharora** [comment]
@mariobehling , do you want something like that .
1. What is the role of the Menu Button then ?

**Comment by mariobehling** [comment]
@aayusharora Yes, please.

**Comment by mariobehling** [comment]
@aayusharora the menu button shows the may 5 sessions. please dont change.

**Comment by aayusharora** [comment]
@mariobehling , I think you are talking about the dropdown "Thu , May 5" sessions , but I am talking about the "Menu" button that appears on right top in mobile size . Till now it was displaying these icons on click , but now icons are shifted above .
I don't think it has utility now .

**Comment by mariobehling** [comment]
@aayusharora I think you are confusing things. The menu button is necessary in small mobile sizes. Please check. Icons need to go up there.

**Comment by niranjan94** [comment]
This issue is resolved now ... Right ? By OpenTechSummit/open-event-scraper#19 .

**Comment by aayusharora** [comment]
@niranjan94 , working it is not align yet , give me a minute.

**Comment by niranjan94** [comment]
@aayusharora My bad :sweat_smile: ... Take your time :smile:

**Comment by aayusharora** [comment]
@mariobehling  , solved here #35 :) , { will generate my repo for preview soon }
