### ISSUE TITLE
Submenu partly hidden in mobile/small screen view

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#31]
Please see screenshot below.
![screenshot from 2016-04-28 12 25 37](https://cloud.githubusercontent.com/assets/1583873/14883124/aa0739ac-0d3c-11e6-8e88-2309e5b16e4a.png)

**Comment by shivamMg** [comment]
@mariobehling The `day-menu` id had some styles defined that made the drop-down to toggle on hover. Hover property is useless on mobile devices, and on desktops it hides the date by toggling drop-down over it. It looks much better with the default drop-down properties. [This](https://github.com/OpenTechSummit/open-event-scraper/pull/20) takes out the `day-menu` id, and I've [removed](https://github.com/OpenTechSummit/2016.opentechsummit.net/pull/32) css defined for it (as it would go unused).

**Comment by niranjan94** [comment]
@shivamMg see closed issue #8 ... That's the reason the hover was added. We could adjust the `top` property such that the day is not hidden in desktop.

**Comment by niranjan94** [comment]
We could also put the hover styles inside a media-query such that they're not considered on a mobile device.

**Comment by aayusharora** [comment]
@mariobehling  , @shivamMg  , working for the same ,Why we are not concerned with hover .

**Comment by aayusharora** [comment]
@shivamMg , I got it , the hover seems confusing to me , a click with a toggle is already there , removing hover for mobile is best option .

**Comment by shivamMg** [comment]
@niranjan94 I still think it's better to have a simple drop-down. The one now, opens up over the date, effectively hiding it. Let @mariobehling decide. If he says, I'll make changes accordingly. Here's a [screenshot](https://i.imgur.com/Iqp7tnk.png) of how it looks now.

**Comment by niranjan94** [comment]
@mariobehling @shivamMg Check this out. 
https://niranjan94.github.io/2016.opentechsummit.net/programm/

**Comment by niranjan94** [comment]
#33 retains the hover feature and fixes the issues :smile:

**Comment by shivamMg** [comment]
@niranjan94 Looks much better :+1: 

Closing this in favor of https://github.com/OpenTechSummit/2016.opentechsummit.net/pull/33

**Comment by shivamMg** [comment]
Lol! I closed the issue instead of the PR :sweat_smile: . Reopening now.

**Comment by mariobehling** [comment]
Issue still persists on Android 4. Tested on Samsung Nexus.

**Comment by mariobehling** [comment]
Sorry, my mistake. Needed a hard refresh. All good.
