### ISSUE TITLE
Removal of unused files on the repo

### ISSUE THREAD

**Issue by niranjan94** [OpenTechSummit/2016.opentechsummit.net#34]
The following **28 files** are unused and could be removed. @mariobehling what do you think ?
- [x] `css/theme-camaro.css`
- [x] `css/theme-dandelion.css`
- [x] `css/theme-debbie.css`
- [x] `css/theme-deepblue.css`
- [x] `css/theme-grass.css`
- [x] `css/theme-gunmetalpurple.css`
- [x] `css/theme-haemo.css`
- [x] `css/theme-handbag.css`
- [x] `css/theme-hot.css`
- [x] `css/theme-humblebumble.css`
- [x] `css/theme-jaded.css`
- [x] `css/theme-lava.css`
- [x] `css/theme-leaf.css`
- [x] `css/theme-lightjade.css`
- [x] `css/theme-lime.css`
- [x] `css/theme-lippy.css`
- [x] `css/theme-meadowlea.css`
- [x] `css/theme-oceanfloor.css`
- [x] `css/theme-pivot.css`
- [x] `css/theme-powerpuff.css`
- [x] `css/theme-properorange.css`
- [x] `css/theme-sulphur.css`
- [x] `css/theme.css`
- [x] `home-2.html`
- [x] `home-3.html`
- [x] `home-4.html`
- [x] `home-5.html`
- [x] `impressum.html`

**Comment by aayusharora** [comment]
@mariobehling  I think , It can be closed for now . Closing this :)
