### ISSUE TITLE
Schedule: Some photos are not added

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#37]
Some photos of speakers are not generated in the schedule. 
![screenshot from 2016-04-29 09 06 25](https://cloud.githubusercontent.com/assets/1583873/14909983/c5f62698-0de9-11e6-98a3-60395768b983.png)

Added some manually now, but they are not generated through the script.

**Comment by shivamMg** [comment]
@mariobehling Do you mean after running `scraper.py` and `event.py`?

**Comment by mariobehling** [comment]
@shivamMg Yes.

**Comment by shivamMg** [comment]
@mariobehling I ran the script and it is extracting these images (the ones missing in the screenshot). I think when you accessed the page at that point the images were not included in the speakers directory. The image tag was rendered, that means it must had a URL (src).

**Comment by mariobehling** [comment]
@shivamMg Try to run it on your repository. Images do not get rendered. When i add a new image it does not work.

**Comment by shivamMg** [comment]
@mariobehling I'm a little confused. They seem to be working on my repo.

> When i add a new image it does not work.

Where do you add the image?

**Comment by mariobehling** [comment]
a new speaker with an image - in the spreadsheet.

**Comment by shivamMg** [comment]
@mariobehling can you come on gitter channel, i need to understand the flow.

**Comment by mananwason** [comment]
@mariobehling Can you share an example. As I see, all images are visible on the main website [here](http://opentechsummit.net/programm/)

**Comment by shivamMg** [comment]
@mariobehling Alright, you're right. Many images are not being downloaded by the scraper, or if they are, they are not proper images.

@mananwason See "IBM Cloud Storage" and below. You won't see any images.

**Comment by mananwason** [comment]
@shivamMg That's not what @mariobehling is talking about I suppose because those images are not visible as they're not listed in the sheets. If not, can you point me to one case where the photo is missing and it's listed in the sheets.

**Comment by shivamMg** [comment]
@mananwason can you come over to the channel?

**Comment by mananwason** [comment]
@mariobehling I think this is resolved, so closing it.
