### ISSUE TITLE
Schedule: Change time format from AM/PM to continental 24h format

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#39]
e.g. instead of 1 pm change to 13:00

Could be changed in spreadsheet and then in scraper.

**Comment by shivamMg** [comment]
@mariobehling Here: https://github.com/OpenTechSummit/open-event-scraper/pull/22

**Comment by shivamMg** [comment]
@mariobehling https://github.com/OpenTechSummit/open-event-scraper/pull/22

**Comment by mariobehling** [comment]
@shivamMg Good job!
