### ISSUE TITLE
Change Date format to include German

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#40]
Change the date format to

**Do. 5. Mai / Thu. 5th May**

so both German and English show up instead of "Thu, 5th May" only.

**Comment by championswimmer** [comment]
Will do this.

**Comment by championswimmer** [comment]
@mariobehling It should always show both formats, or any option to select German/English ?

**Comment by mariobehling** [comment]
@championswimmer Thank you. Now, please 
- [x] move German to front 
- [x] take out "0". 
- [x] "." behind number in German

Format should be:

**Do. 5. Mai / Thu. 5th May**
![screenshot from 2016-05-01 11 51 51](https://cloud.githubusercontent.com/assets/1583873/14941189/44e1ea3c-0f93-11e6-964c-7837b41ff0ec.png)

**Comment by championswimmer** [comment]
Take out zero from both English and German ?

**Comment by championswimmer** [comment]
@mariobehling done here https://github.com/OpenTechSummit/open-event-scraper/pull/24

**Comment by mariobehling** [comment]
Good job! It is a good practice to work together on some small issues at the beginning. Let's pay attention to those small things to save us all some time over the summer.

**Comment by championswimmer** [comment]
Yes definitely :)
