### ISSUE TITLE
Implement Logo Image and Ico in Scraper, JSON and Website

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#41]
I have added a new sheet "Images" to the spreadsheet. Please get the logo and ico from here in the same way as the pictures of speakers.

The logo on the top left should be linked to the link to the URL defined in the sheet "Event" in the row "Event Main Page"

**Comment by shivamMg** [comment]
@mariobehling https://github.com/OpenTechSummit/open-event-scraper/pull/26

Copy&Paste the downloaded Logo and Ico images the same way you do with Speaker images.

**Comment by mariobehling** [comment]
Please do not put these images in speakers image folder. They should go in /img subfolder.

Reverted your last commit as it did not show the logo. Please add a link to your github pages fork, so we can see the changes working in future.

![screenshot from 2016-05-02 11 21 53](https://cloud.githubusercontent.com/assets/1583873/14951375/c12cbc78-1058-11e6-9f80-ee474d9ae012.png)

**Comment by shivamMg** [comment]
@mariobehling Working on it now.

**Comment by shivamMg** [comment]
@mariobehling Here: https://github.com/OpenTechSummit/open-event-scraper/pull/28

**Comment by mariobehling** [comment]
@shivamMg All programm data should be in one folder (2016.opentechsummit.net/programm). Apparently you now put the images into a folder above. Please add images into 2016.opentechsummit.net/programm/img/ and keep speakers in the folder 2016.opentechsummit.net/programm/speakers/

**Comment by shivamMg** [comment]
@mariobehling https://github.com/OpenTechSummit/open-event-scraper/pull/32: The image links generated will now link to `programm/img` dir. But this requires a `programm/img` dir which currently does not exist. So you need to merge this too: https://github.com/OpenTechSummit/2016.opentechsummit.net/pull/51

Demo: https://shivammg.github.io/2016.opentechsummit.net/programm/

**Comment by mariobehling** [comment]
I do not know why you made a PR here. The scraper should do all the work. I merged your PR in the scraper, but there is a problem. The folder is img/img. Please check.

![screenshot from 2016-05-30 17 17 15](https://cloud.githubusercontent.com/assets/1583873/15653015/83985186-268a-11e6-8cd8-859508376f6e.png)

**Comment by shivamMg** [comment]
@mariobehling I didn't write the correct rsync command for build.sh. It was copying entire directory instead of just images. This should fix it: https://github.com/OpenTechSummit/open-event-scraper/pull/33

**Comment by shivamMg** [comment]
Implemented at https://github.com/OpenTechSummit/open-event-scraper/pull/33 and https://github.com/OpenTechSummit/open-event-scraper/pull/32
