### ISSUE TITLE
What possibilities are there to tweet the sessions automatically

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#42]
How could we tweet the sessions automatically including 
- Session topic
- Speaker twitter name e.g. @speakername
- now at "Event Hashtags" e.g. #OTS #Berlin
- the speaker photo
- link to the sessions

E.g. Suchmaschinen der Zukunft @0rb1t3r now at #OTS #Berlin http://opentechsummit.net/programm/#OT-10

**Comment by championswimmer** [comment]
Doesn't twitter allow tweet scheduling?

**Comment by mariobehling** [comment]
@championswimmer Actually, I am looking for answers not questions. It would be great, if you help to research. There is tweetdeck, that has scheduling features, but we need a more automatic way to schedule tweets that are generated from the JSON.

**Comment by SaptakS** [comment]
We can create a cronjob to check at regular interval the json files and find if there is some session at that time. If there is a session, we can post that in twitter. For automating posting in twitter, we can use this: https://videlais.com/2015/03/02/how-to-create-a-basic-twitterbot-in-python/

**Comment by championswimmer** [comment]
@mariobehling We are to assume the schedule can change till the last moment
right?

Yes it will need to be a cron job type of thing.

Yes there is an api at Twitter for scheduling tweets, I looked that up.
I am looking at how a cron job can be used to trigger the tweets.

**Comment by aviaryan** [comment]
AppVeyor CI looks to have a good cron scheduling feature. https://www.appveyor.com/docs/build-configuration#scheduled-builds
TravisCI has no cron and CircleCI has a very limited (nightly) cron. 
We can use AppVeyor to run builds every 5 or 10 mins that will run a script (in Python, Tweepy) that takes the output json and tweet out sessions in nearby time range. 

Another very easy way to setup would be using IFTTT and [Google Calendar and Twitter integration](https://ifttt.com/connect/google_calendar/twitter). As we have the calendar ready at #21, it would be easy to setup but this will come with a limitation that we won't be able to tweet speaker's handle and photo .

**Comment by mariobehling** [comment]
Let's follow up on this feature in the fossasia open event app.
