### ISSUE TITLE
loklak fetcher only shows very old tweets

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#43]
Any ideas? I looked at the config. Looks correct to me.

![screenshot from 2016-05-01 12 33 14](https://cloud.githubusercontent.com/assets/1583873/14941381/062da3fc-0f99-11e6-8698-f3db46bcf3a3.png)

**Comment by rafalkowalski** [comment]
I'm not able to reproduce this bug

**Comment by jigyasa-grover** [comment]
Same here @mariobehling . It shows latest (1 day old) tweets here.

![screenshot from 2016-05-01 18 23 11](https://cloud.githubusercontent.com/assets/9291400/14941891/ec39062c-0fc9-11e6-8c30-abd333af2406.png)

**Comment by mariobehling** [comment]
PR has been merged already. Issue is fixed. Thanks!
