### ISSUE TITLE
Schedule: Text of description is bold in Firefox

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#46]
It should not be bold. Cannot see where the change happened.

![screenshot from 2016-05-02 11 04 54](https://cloud.githubusercontent.com/assets/1583873/14950974/1690bb2c-1056-11e6-9f9d-d861669cd7e1.png)

**Comment by aayusharora** [comment]
@mariobehling , Solving it

**Comment by the-dagger** [comment]
@mariobehling Seems to works fine here.
![selection_015](https://cloud.githubusercontent.com/assets/6565270/14953980/3a926f12-108c-11e6-9ac6-8c16a06191b7.png)

**Comment by mariobehling** [comment]
This is weird. I wonder if it is related to Google fonts. I had some blocking of Google as they seemed to have a lot of traffic from my IP range.

**Comment by the-dagger** [comment]
I double checked this by booting into windows and it works perfectly fine there too.

**Comment by championswimmer** [comment]
Working fine for me too

**Comment by aayusharora** [comment]
@mariobehling  I have checked it on two systems , its working fine for me , but it is firefox version dependent . Also , I have checked all the CSS and find nothing , the problem I have figured out is with Open Sans font , which render differently for Firefox and chrome , Problem is with Version 47.0  Beta 1 firefox.
