### ISSUE TITLE
Schedule: Links - website, github etc. - are not generated for session

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#47]
The Nitrokey session does not show the links that are listed in the spreadsheet.

![screenshot from 2016-05-02 11 54 38](https://cloud.githubusercontent.com/assets/1583873/14951944/ca2dad7e-105c-11e6-91c2-f2609020d557.png)

**Comment by rafalkowalski** [comment]
@mariobehling i've discovered where bug occured. You have to add some Bio to spreadsheet to Jan Suhr(Nitrokey)

**Comment by mariobehling** [comment]
Ok, yes, that solved it. Cheers!
