### ISSUE TITLE
Implement Audio field for sessions similar to video

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#49]
We have an rss feed with links to audio files here https://voicerepublic.com/series/open-tech-summit-2016.rss
- [x] Add audio links to spreadsheet manually (OTS1 and OTS2) from above rss file
- [x] Scrape audio files and add them into subfolder /audio
- [x] Add audio button into program with a link

**Comment by mariobehling** [comment]
Unfortunately the tracks are not rendered anymore after this update: http://2016.opentechsummit.net/programm/

**Comment by mariobehling** [comment]
Also item number 2 is not implemented. Please add the audio files into a subfolder. This can be generated just like the speaker photos.

**Comment by championswimmer** [comment]
@mariobehling 

I can play the audios right now at http://2016.opentechsummit.net/programm/ 
please recheck ?

**Comment by mariobehling** [comment]
Please read carefully my previous comments.
- [x] Scrape audio files and **add them into subfolder /audio**
- [x] The sessions are not sorted into tracks anymore

![screenshot from 2016-05-28 16 41 33](https://cloud.githubusercontent.com/assets/1583873/15627908/7a96cc36-24f3-11e6-82fe-682ffd7c9232.png)

**Comment by championswimmer** [comment]
@mariobehling I am working on the audio downloading part, but the track going blank cannot be due to my commit.

Check https://github.com/OpenTechSummit/open-event-scraper/commit/3a6d563bec37801f48c6180bd04e68af67e29bb9
There is no way my code could regress the track folding. 

I'll take a look at it anyway.

**Comment by championswimmer** [comment]
It could be because of this 
https://github.com/OpenTechSummit/open-event-scraper/commit/ce6575d7e1bcd2d5948a60757bbfa9d56449de08

@mananwason please check if that was regression because of your commit ?

**Comment by mananwason** [comment]
@mariobehling @championswimmer Fixed the tracks.

**Comment by championswimmer** [comment]
@mariobehling please take a look at this PR for saving mp3 files locally

https://github.com/OpenTechSummit/open-event-scraper/pull/31

**Comment by mariobehling** [comment]
Thanks! Closing it.
