### ISSUE TITLE
Add sponsors on bottom of page with image

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#53]
I added a sheet "sponsors" to the spreadsheet. Please add a section "sponsors" to the end of the page with a list of logos in a row.
- [x] Create Sections based on Levels from the sheet
- [ ] Add logos into the folder /programm/img
- [x] Add links to logos
- [x] Create Alt tags based on name of sponsor

**Comment by aayusharora** [comment]
@championswimmer , seems like , we can divide this work.

**Comment by championswimmer** [comment]
The required functionality of this issue is done. We still need to fixup the css and alignment here and there
