### ISSUE TITLE
Add Copyright Notice to footer of page

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#54]
Information on Copyright is available no at the end of the site. Please add a footer for this info to the very bottom of the page.

**Comment by championswimmer** [comment]
```
Copyright (c) 2016, OpenTechSummit
```

That is good ?

**Comment by mariobehling** [comment]
Please look in the spreadsheet. It should be generated from the JSON as well.

**Comment by championswimmer** [comment]
Ok I got it 👍

**Comment by championswimmer** [comment]
<img width="1216" alt="screen shot 2016-06-03 at 11 00 55 am" src="https://cloud.githubusercontent.com/assets/1327050/15769626/7be795e4-297a-11e6-8964-f16906ad5bf1.png">
Done

**Comment by mariobehling** [comment]
I just generated the schedule. Does have issues. Please have a look.
http://2016.opentechsummit.net/programm/
- [ ] Please add the link to the image

**Comment by aayusharora** [comment]
@mariobehling  , solved here https://github.com/OpenTechSummit/open-event-scraper/pull/39 .
![3](https://cloud.githubusercontent.com/assets/12194719/15800106/9f618e12-2a79-11e6-87fe-1a75cd283f1c.png)

**Comment by championswimmer** [comment]
@mariobehling where should the link point to ?

**Comment by championswimmer** [comment]
Ok done. Copyright image is linked to license page. 
The text **OpenTechSummit** links to OTS page.
