### ISSUE TITLE
Also write JSON files as a reference into the folder when generating the web app

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#55]
Please include the JSON files in the directory /programm/json/

**Comment by aayusharora** [comment]
@mariobehling , Working on it .

**Comment by aayusharora** [comment]
@mariobehling  , @championswimmer  , Please see https://github.com/OpenTechSummit/open-event-scraper/pulls
Also we have to create an empty json folder in this repo under programm .

**Comment by aayusharora** [comment]
@championswimmer , Do we still need to take jsons of this repo in the programm folder , as now after running build.sh it will add it to json folder .
Should I remove the jsons from this repo or Should I paste them in the  programm/json ?

**Comment by championswimmer** [comment]
Clean the jsons that are here. It'll get automatically copied from now on

**Comment by aayusharora** [comment]
But I cant commit a blank folder name json

**Comment by aayusharora** [comment]
I need to have some files in it @championswimmer , I guess I should put jsons in programm/jsons

**Comment by championswimmer** [comment]
For blank folders just add a empty .gitignore to the folder and add it :D

**Comment by aayusharora** [comment]
@championswimmer  @mariobehling , Check this #56 Done

**Comment by mariobehling** [comment]
Good job. It is done through the scraper as desired.
