### ISSUE TITLE
Make schedule "self-containing" and generate css and all required files for web app in the subfolder

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#59]
The subfolder /programm is the place to keep all files for the schedule. We want to be able to move this schedule (programm) to any location on the web. E.g. we could save it as a zip and deploy it somewhere else.

Please generate the css and any other files in the folder or subfolder of /programm through the script.

**Comment by aayusharora** [comment]
@mariobehling , Working on it .

**Comment by aayusharora** [comment]
@mariobehling ,
1. I need a bit clearance for this . Should it be like a generic folder like programm , that contains all the files needed for index.html to work  .
2 .This will be done by making a build.sh in scraper repo , that after running will perform the above task.

**Comment by mariobehling** [comment]
Ok, I don't know how you think the scraper is related to this. I can only repeat myself. The folder needs to work if I copy it somewhere else. If the css is in another folder it does not work.
@championswimmer Please help @aayusharora to clear up questions.

**Comment by aayusharora** [comment]
Ok thanks @mariobehling

**Comment by championswimmer** [comment]
@aayusharora 
Right now, index.html in the programm folder depends on js/css includes from the root of the project. 
What @mariobehling means to say is, make the `programm` folder fully self sufficient. Any of the required css and js files to be present in programm folder itself. Without needing the root directory.

**Comment by aayusharora** [comment]
@championswimmer ,@mariobehling , solved here #60

**Comment by mariobehling** [comment]
@aayusharora Ok, looks like you updated the location of the css files, but not the location of the js files.

@championswimmer @aayusharora Also: Let's assume we have an empty repository and there is nothing inside. We want to generate the whole web app. Where do the css and js files come from?

**Comment by aayusharora** [comment]
@mariobehling , Consider this  #62 to generate CSS , JS files in empty repo, I have explained it , the issue is related .

**Comment by aayusharora** [comment]
@mariobehling , Working for the empty repository part to generate whole webapp .

**Comment by aayusharora** [comment]
@mariobehling @championswimmer  it is solved https://github.com/OpenTechSummit/open-event-scraper/pull/37
