### ISSUE TITLE
CSS for Sponsor section

### ISSUE THREAD

**Issue by aayusharora** [OpenTechSummit/2016.opentechsummit.net#66]
@mariobehling @championswimmer  solved by PR https://github.com/OpenTechSummit/open-event-scraper/pull/39

**Comment by aayusharora** [comment]
![logo](https://cloud.githubusercontent.com/assets/12194719/15799926/bfce2d6c-2a75-11e6-9ac6-4f5f8252904c.png)

**Comment by aayusharora** [comment]
![5](https://cloud.githubusercontent.com/assets/12194719/15800319/641c81a4-2a7e-11e6-930a-d76a241b663e.png)

**Comment by mariobehling** [comment]
Scaling is not done correctly. Width and length arent scaled in proportion.

**Comment by aayusharora** [comment]
![9](https://cloud.githubusercontent.com/assets/12194719/15800974/3a3e8f96-2a90-11e6-9c14-70c02262ca22.png)

**Comment by aayusharora** [comment]
@mariobehling  , scaling done .
![8](https://cloud.githubusercontent.com/assets/12194719/15801005/fe2b8738-2a90-11e6-8cfc-c0f107cbc601.png)

**Comment by championswimmer** [comment]
Cool. I'll merge the PR and connect the generator right now then

**Comment by championswimmer** [comment]
Please check the generated page right now. 
There are some more things to fix. 
Can you generate a markup that does **not** need md-offset ? Because we should not depend on the 1st item of array to have offset when doing via generator.js. If you can center the row without offset would be great.

**Comment by aayusharora** [comment]
@championswimmer , will do it

**Comment by aayusharora** [comment]
@championswimmer  Done !! check  https://github.com/OpenTechSummit/open-event-scraper/pull/40
