### ISSUE TITLE
Schedule: Linkify links in description e.g. of Nicco Kunzmann

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#7]
![screenshot from 2016-04-25 19 25 37](https://cloud.githubusercontent.com/assets/1583873/14792660/946c1bb2-0b1b-11e6-9bcb-99337ee59330.png)

**Comment by mariobehling** [comment]
@niranjan94 Please also linkify links in bio info, e.g. here http://opentechsummit.net/programm/#MS-15

**Comment by niranjan94** [comment]
@mariobehling will do

**Comment by mariobehling** [comment]
@niranjan94 looks like the changes resulted in getting the description and everything bold.

![screenshot from 2016-05-01 23 23 14](https://cloud.githubusercontent.com/assets/1583873/14944467/e76b32d0-0ff3-11e6-9c4c-3988e58f1248.png)

**Comment by niranjan94** [comment]
@mariobehling no I don't think this commit caused that. 
You can see the demo here: http://opentechsummit.net/programm/#MS-15 

Everything seems to be fine.

**Comment by mariobehling** [comment]
Ok, I am opening an new issue. The bold text is there with Firefox.
