### ISSUE TITLE
Schedule: Expand day menu on scroll over / Link to day section / smooth scrolling

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/2016.opentechsummit.net#8]
- [x] Expand day menu on scroll over
- [x] implement smooth scrolling like on main page

**Comment by niranjan94** [comment]
@mariobehling I don't notice any smooth scrolling on the main page. Which one do you mean ?

**Comment by mariobehling** [comment]
Please go to main page and click on the top menu "Presse". Instead of jumping it auto scrolls the page.
